apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "org.tiny.example"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "0.1"
    }
    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
